### ISSUE TITLE
Pull to #Powershell/Powershell

### ISSUE THREAD

**Issue by SRGOM** [mnaoumov/Add-GlobalResult#2]
There's no license here so I don't know but if @vors is interested in this, any chance you could set a license/send a pull request?

**Comment by mnaoumov** [comment]
@SRGOM this project is a totally dirty workaround. If even @vors would be interested to bring this functionality in the core PowerShell he would never merge my project, he would just implement this basic functionality from scratch using proper PowerShell internals

**Comment by mnaoumov** [comment]
@SRGOM I set MIT license so I think the issue can be closed now

**Comment by vors** [comment]
Thank you for setting the license!
As I mentioned on gitter, adding a new variable is a breaking change (people may have they own variables with the same name).
At the meantime, since you already did the work, I would suggest to publish it to the gallery. Maybe wrap it into a module at the same time, but gallery now supports scripts too.
